export const ENDPOINTS = {
  auth: {
    register:       '/auth/register/',
    login:          '/auth/login/',
    refresh:        '/auth/refresh/',
    me:             '/auth/me/',
    logout:         '/auth/logout/',
    changePassword: '/auth/change-password/',
  },
  songs: {
    generate:      '/songs/generate/',
    job:           (jobId: string)    => `/songs/jobs/${jobId}/`,
    playUrl:       (songId: string)   => `/songs/${songId}/play-url/`,
    thumbnailUrl:  (songId: string)   => `/songs/${songId}/thumbnail-url/`,
    library:       '/songs/library/',
    detail:       (id: string) => `/songs/${id}/`,
    update:       (id: string) => `/songs/${id}/`,
    delete:       (id: string) => `/songs/${id}/`,
    like:         (id: string) => `/songs/${id}/like/`,
    tags:         '/songs/tags/',
  },
  credits: {
    balance:             '/credits/balance/',
    plans:               '/credits/plans/',
    planDetail:          (id: number | string) => `/credits/plans/${id}/`,
    checkout:            '/credits/checkout/',
    stripeWebhook:       '/credits/stripe-webhook/',
    transactions:        '/credits/transactions/',
    pay:                 '/credits/pay/',
    paymentMethods:      '/credits/payment-methods/',
    paymentMethodDetail: (id: number | string) => `/credits/payment-methods/${id}/`,
    subscriptions:       '/credits/subscriptions/',
    stripePrices:        '/credits/stripe/prices/',
    stripePriceDetail:   (id: string) => `/credits/stripe/prices/${id}/`,
  },
  community: {
    feed:     '/community/feed/',
    trending: '/community/trending/',
    stats:    '/community/stats/',
    like:     (id: string) => `/community/songs/${id}/like/`,
    play:     (id: string) => `/community/songs/${id}/play/`,
  },
  notifications: {
    list:       '/notifications/',
    markRead:   (id: number) => `/notifications/${id}/read/`,
    markAllRead:'/notifications/read-all/',
  },
  stems: {
    separate: '/stems/separate/',
    jobs: '/stems/jobs/',
    jobStatus: (jobId: string) => `/stems/jobs/${jobId}/`,
    downloadUrl: (fileId: string) => `/stems/files/${fileId}/download-url/`,
  },
  recommendations: {
    forYou:        '/recommendations/for-you/',
    suggestedTags: '/recommendations/suggested-tags/',
  },
  playlists: {
    list:         '/playlists/',
    detail:       (id: string) => `/playlists/${id}/`,
    songs:        (id: string) => `/playlists/${id}/songs/`,
    songRemove:   (id: string, songId: string) => `/playlists/${id}/songs/${songId}/`,
    share:        (id: string) => `/playlists/${id}/share/`,
    public:       (token: string) => `/playlists/public/${token}/`,
    auto:         '/playlists/auto/',
    autoGenerate: '/playlists/auto/generate/',
  },
  reports: {
    usage:     '/reports/usage/',
    topSongs:  '/reports/top-songs/',
    auditLogs: '/reports/audit-logs/',
    users:     '/reports/users/',
  },
  mix: {
    projects:    '/mix/projects/',
    project:     (id: string) => `/mix/projects/${id}/`,
    clips:       (mixId: string) => `/mix/projects/${mixId}/clips/`,
    clip:        (mixId: string, clipId: string) => `/mix/projects/${mixId}/clips/${clipId}/`,
    reorder:     (mixId: string) => `/mix/projects/${mixId}/reorder/`,
    export:      (mixId: string) => `/mix/projects/${mixId}/export/`,
    exportStatus:(exportId: string) => `/mix/exports/${exportId}/`,
  },
} as const
