export const ENDPOINTS = {
  auth: {
    register:       '/auth/register/',
    login:          '/auth/login/',
    refresh:        '/auth/refresh/',
    me:             '/auth/me/',
    logout:         '/auth/logout/',
    changePassword: '/auth/change-password/',
  },
  songs: {
    generate:      '/songs/generate/',
    job:           (jobId: string)    => `/songs/jobs/${jobId}/`,
    playUrl:       (songId: string)   => `/songs/${songId}/play-url/`,
    thumbnailUrl:  (songId: string)   => `/songs/${songId}/thumbnail-url/`,
    library:       '/songs/library/',
    detail:       (id: string) => `/songs/${id}/`,
    update:       (id: string) => `/songs/${id}/`,
    delete:       (id: string) => `/songs/${id}/`,
    like:         (id: string) => `/songs/${id}/like/`,
    tags:         '/songs/tags/',
  },
  credits: {
    balance:             '/credits/balance/',
    plans:               '/credits/plans/',
    planDetail:          (id: number | string) => `/credits/plans/${id}/`,
    checkout:            '/credits/checkout/',
    stripeWebhook:       '/credits/stripe-webhook/',
    transactions:        '/credits/transactions/',
    pay:                 '/credits/pay/',
    paymentMethods:      '/credits/payment-methods/',
    paymentMethodDetail: (id: number | string) => `/credits/payment-methods/${id}/`,
    subscriptions:       '/credits/subscriptions/',
    stripePrices:        '/credits/stripe/prices/',
    stripePriceDetail:   (id: string) => `/credits/stripe/prices/${id}/`,
  },
  community: {
    trending: '/community/trending/',
    feed:     '/community/feed/',
    plays:    '/community/plays/',
  },

} as const
